CREATE SCHEMA IF NOT EXISTS product_;

CREATE TABLE product_.lao_exclusions (id INTEGER primary key generated by default as identity, crn TEXT, user_id TEXT, reason TEXT, since TIMESTAMPTZ, until TIMESTAMPTZ);

CREATE TABLE product_.lao_restrictions (id INTEGER primary key generated by default as identity, crn TEXT, user_id TEXT, reason TEXT, since TIMESTAMPTZ, until TIMESTAMPTZ);