hmpps.sqs:
  provider: localstack
  queues:
    inboundqueue:
      queueName: inbound-queue
      dlqName: inbound-dlq
      subscribeTopicId: inboundtopic
      subscribeFilter: '{"eventType":[ "probation-case.restriction.updated", "probation-case.exclusion.updated"] }'
  topics:
    inboundtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:inbound-topic