generic-service:
  nameOverride: digital-prison-reporting-lao-domain-events-processor
  productId: "UNASSIGNED" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 1

  image:
    repository: ghcr.io/ministryofjustice/digital-prison-reporting-lao-domain-events-processor
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-digital-prison-reporting-mi-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    JAVA_OPTS: "-Xmx512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SENTRY_TRACES_SAMPLE_RATE: '0.05'
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: "org.apache.catalina.connector.ClientAbortException"

  namespace_secrets:
    digital-prison-reporting-lao-domain-events-processor-client-creds:
      API_CLIENT_CREDENTIALS_ID: "api_client_credentials_id"
      API_CLIENT_CREDENTIALS_SECRET: "api_client_credentials_secret"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_INBOUNDTOPIC_ARN: "topic_arn"
    sqs-domain-events-secret:
      INBOUND_QUEUE_NAME: "queue_name"
    sqs-domain-events-dlq-secret:
      INBOUND_DLQ_QUEUE_NAME: "queue_name"
    digital-prison-reporting-lao-domain-events-processor-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    redshift-jdbc:
      REDSHIFT_JDBC_USER: "user"
      REDSHIFT_JDBC_PASSWORD: "password"
      REDSHIFT_JDBC_URL: "url"
    redshift-data:
      REDSHIFT_DATA_SECRETARN: "secretarn"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: digital-prison-reporting-lao-domain-events-processor
