---

generic-service:
  serviceAccountName: "dpr-reporting-mi-development-cross-iam"

  ingress:
    host: dpr-lao-domain-events-processor-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    LAODATA_HOST: "https://probation-access-control-dev.hmpps.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '40 7 * * 1-5' # Start at 7.40am UTC Monday-Friday
    shutdown: '20 20 * * 1-5' # Stop at 8.20pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: probation-frontend-alerts-dev
